<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="main.css">
    <title><?= $config->site_title() ?></title>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1><a href="./"><?= $config->site_title() ?></a></h1>
      </div>
      <div class="body">
        <aside class="sidebar">
          <div class="sidebar-section">
            <h2>Getting Started</h2>
            <ul>
              <li><a href="./">Introduction</a></li>
              <li><a href="./first">Your First Page</a></li>
              <li><a href="./deployment">Deployment</a></li>
            </ul>
          </div>
          <div class="sidebar-section">
            <h2>Cutomization</h2>
            <ul>
              <li><a href="./config">Configuration</a></li>
              <li><a href="./variables">Variables</a></li>
              <li><a href="./template">Template</a></li>
            </ul>
          </div>
        </aside>
        <div class="main">
          <h2><?= $title ?></h2>
          <?= $content ?>
        </div>
      </div>
      <div class="footer">
          This site is generated by <a href="https://github.com/kentaro/soushi">Soushi</a> and created by <a href="http://kentarok.org">Kentaro Kuribayashi</a>.
      </div>
    </div>
  </body>
</html>
