<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="main.css">
    <title><?= $config->siteTitle ?></title>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1><?= $config->siteTitle ?></h1>
      </div>
      <div class="body">
        <h2><?= $title ?></h2>
        <?= $content ?>
      </div>
      <div class="footer">
        This site is generated by <a href="https://github.com/kentaro/soushi">Soushi</a> and created by <a href="http://kentarok.org">Kentaro Kuribayashi</a>.
      </div>
    </div>
  </body>
</html>
